### PR TITLE
Use Eldev for project infrastructure; add test framework and a CI workflow

### PR DESCRIPTION
**Pull request by doublep**
As discussed in issue #33.

* Add Eldev to manage the Elisp package in general. Its use is not required and is not forced on anyone (not even developers, much less end-users). However, I do recommend using it at least for development.
* Add standard Elisp package headers to `lspce.el` (only comments, doesn't affect functionality). Eldev needs this: it requires that projects have metadata, e.g. declare their dependencies.
* Modify `.gitignore` to remove the generic stuff and actually adapt to the project.
* Add two tests (note FIXME in one of them: I suspect it highlights a bug in LSPCE). The tests use JDTLS (a Java LSP-server) and are automatically skipped if it is not installed.
* Add a GitHub workflow that will run the tests automatically on every commit (continuous integration) and alert committer when something breaks.
* Configure GitHub's Dependabot (will create automated PRs for the worklfow in the future).

If this gets accepted, I'll update `README.org` as appropriate. However, as mentioned above, this is purely an addition, it doesn't invalidate any existing installation methods.

### CODE REVIEW

**Comment by zbelial** [comment]
Hi @doublep, thanks very much and sorry for late relay. I was so busy in the past few days, and I'll be busy for at least severy days. I'll deal with merging when I'm free. 
Thanks again.

**Comment by zbelial** [comment]
Hi @doublep , sorry for the late response, I just merged your PR into a branch `eldev`. After getting a little familiar with eldev and this PR, I'll merge it into the master branch. Thanks.

**Comment by doublep** [comment]
Feel free to use if you want, but I'm not interested in developing anything at this rate.

**Comment by zbelial** [comment]
Hi @doublep , sorry, it's all my fault. Normally it wouldn't need this so long time to get a PR merged. I started to prepare an immportant exam to get a cerfication in April, and I just finished this Tuesday, and during this period of time, I had busy work and also switched department and so on. So not in the mood for dealing with other things. 
But anyway, thank you again for putting effort for helping improve this package.

**Pull request closed without merging**
